module.exports = {
  content: ["./static/index.html"],
  safelist: [
    "bg-amber-500",
    "bg-amber-600",
    "bg-blue-500",
    "bg-blue-600",
    "bg-emerald-500",
    "bg-emerald-600",
    "bg-rose-500",
    "bg-rose-600",
    "border-amber-500",
    "border-blue-500",
    "border-emerald-500",
    "border-rose-500",
    "grid",
    "grid-cols-2",
    "hidden",
    "hover:text-white",
    "opacity-0",
    "scale-95",
    "shadow-lg",
    "shadow-sm",
    "text-amber-500",
    "text-blue-500",
    "text-emerald-400",
    "text-emerald-500",
    "text-red-400",
    "text-rose-500",
    "text-slate-400",
    "text-white",
    "translate-x-full",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
